#!/usr/bin/env bash
set -e # Exit immediately if a command exits with a non-zero status.

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_USER_NAME WITH ENCRYPTED PASSWORD '$POSTGRES_USER_PASSWORD';
    CREATE DATABASE $POSTGRES_DB_NAME;
    ALTER DATABASE $POSTGRES_DB_NAME OWNER TO $POSTGRES_USER_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_NAME TO $POSTGRES_USER_NAME;
EOSQL
