version: '3.7'

networks:
    app-network:
        name: app-network

volumes:
    app_postgresql_data:
        name: app_postgresql_data
    app_mysql_data:
        name: app_mysql_data

services:

    nginx:
        container_name: app-nginx
        image: nginx:1.19.4
        volumes:
            - ../:/srv
            - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - ${NGINX_EXTERNAL_PORT}:80
        networks:
            - app-network
        depends_on:
            - php-fpm

    php-fpm:
        container_name: app-php-fpm
        image: app:php-fpm
        build:
            context: ..
            dockerfile: docker/php/Dockerfile
            args:
                PUID: $PUID
                PGID: $PGID
                PHP_VERSION: $PHP_VERSION
                COMPOSER_VERSION: $COMPOSER_VERSION
                PHP_TYPE: fpm
                GITHUB_TOKEN: $GITHUB_TOKEN
            target: dev
        environment:
            APP_ENV: dev
        volumes:
            - ..:/srv
            - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini
            - $HOME/.composer/cache:/home/dev/.composer/cache
        networks:
            - app-network
        depends_on:
            - postgres
            - mysql
            - memcached

    postgres:
        container_name: app-postgres
        build: postgres
        image: app:postgres
        environment:
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB_NAME=$POSTGRES_DB_NAME
            - POSTGRES_USER_NAME=$POSTGRES_USER_NAME
            - POSTGRES_USER_PASSWORD=$POSTGRES_USER_PASSWORD
        ports:
            - ${POSTGRES_EXTERNAL_PORT}:5432
        volumes:
            - app_postgresql_data:/var/lib/postgresql/data
        networks:
            - app-network

    mysql:
        container_name: app-mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        ports:
            - ${MYSQL_EXTERNAL_PORT}:3306
        volumes:
            - app_mysql_data:/var/lib/mysql
        networks:
            - app-network

    adminer:
        container_name: app-adminer
        image: adminer:4.8.0-standalone
        ports:
            - ${ADMINER_EXTERNAL_PORT}:8080
        networks:
            - app-network

    memcached:
        container_name: app-memcached
        image: memcached:1.6.8
        ports:
            - "${MEMCACHED_EXTERNAL_PORT}:11211"
        networks:
            - app-network

    redis:
        container_name: app-redis
        image: redis:6.0-buster
        networks:
            - app-network